### ISSUE TITLE
Docker Hub shutting down free organizations

### ISSUE THREAD

**Issue by parkr** [octodns/octodns-docker#62]
Docker Hub is shutting down free organizations. https://blog.alexellis.io/docker-is-deleting-open-source-images/

This does not affect the octodns account since it is a user account instead of an organization.

We might want to ensure we have redundancy across multiple container registries anyway.

Cc @ross

**Comment by ross** [comment]
Looks like they've clarified a bit and it's not as bad as it first sounded https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/. There is some sort of open source team offering, but not clue what it is. Regardless fine with diversifying, from dockerhub.
