### ISSUE TITLE
octodns-bind missing from octodns/octodns:all image

### ISSUE THREAD

**Issue by joshsleeper** [octodns/octodns-docker#65]
We have need for an `octodns` container image with a few cloud providers + `octodns-bind`, but were surprised to find that, despite being a first-party provider, `octodns-bind` isn't actually included in `octodns/octodns:all`!

Is there a reason for this that I'm failing to find, or is it simply an oversight we can correct?

also, thanks for helping make + maintain such a great product, `octodns` rules haha

**Comment by ross** [comment]
Hrm. Guessing it was split out after this was created. Will take a look.
